# Generated by Django 5.2.4 on 2025-07-25 13:37

import referral.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20, unique=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('invite_code', models.CharField(default=referral.models.generate_invite_code, max_length=6, unique=True)),
                ('used_invite_code', models.CharField(blank=True, max_length=6, null=True)),
            ],
        ),
    ]
